version: '2'

services:
   salve1:
     build:
       context: ./Slaves
       dockerfile: Dockerfile
     image: hdp_slave
     environment:
       - SPARK_WORKER_WEBUI_PORT=8082
       - SPARK_WORKER_LOG=/spark/logs
       - SPARK_MASTER=127.0.0.1:7077
     network_mode: host
     container_name: hdp_slave1
   salve2:
     build:
       context: ./Slaves
       dockerfile: Dockerfile
     image: hdp_slave
     environment:
       - SPARK_WORKER_WEBUI_PORT=8083
       - SPARK_WORKER_LOG=/spark/logs
       - SPARK_MASTER=127.0.0.1:7077
     network_mode: host
     container_name: hdp_slave2
   master1:
     build:
       context: ./Masters
       dockerfile: Dockerfile
     image: hdp_master
     environment:
       - SPARK_MASTER_PORT=7077
       - SPARK_MASTER_LOG=/spark/logs
       - SPARK_MASTER_WEBUI_PORT=8080
     network_mode: host
     container_name: hdp_master1
